def victory_screen():
    print("\n" * 2)
    print(r"██╗   ██╗██╗ ██████╗████████╗ ██████╗ ██████╗ ██╗   ██╗")
    print(r"██║   ██║██║██╔════╝╚══██╔══╝██╔═══██╗██╔══██╗╚██╗ ██╔╝")
    print(r"██║   ██║██║██║        ██║   ██║   ██║██████╔╝ ╚████╔╝ ")
    print(r"╚██╗ ██╔╝██║██║        ██║   ██║   ██║██╔══██╗  ╚██╔╝  ")
    print(r" ╚████╔╝ ██║╚██████╗   ██║   ╚██████╔╝██║  ██║   ██║   ")
    print(r"  ╚═══╝  ╚═╝ ╚═════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ")
    print("\n")
    print("           You stand victorious in the ruins!")
    print("         The deeper paths now whisper your name.\n")
    print("       Relics & Runes is still in early development.")
    print("         Stronger enemies and relics coming soon.\n")
    input("             Press Enter to continue...")
